
services:
  redis:
    container_name: my-redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command:
      --requirepass "#foVEYdich"
    volumes:
      - ./redis-data/:/data